site_name: junk의 신나는 PS 블로그
theme:
  name: material
  language: ko
  palette:
    scheme: slate
    primary: indigo
    accent: blue
  font:
      text: Noto Serif KR
  features:
    - naviagtion.tabs
    - naviagtion.tracking
    - navigation.indexes
    - navigation.footer

    - search.highlight
    - search.share
    

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  

extra:
  social:
   - icon: fontawesome/brands/github
     link: https://github.com/junk727

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - tags